# Kotlin
kotlin.code.style=official
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true

# Compose
org.jetbrains.compose.experimental.jscanvas.enabled=true

# Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# Performance
org.gradle.daemon=true
org.gradle.workers.max=4
