-- Phase 1: Schema metadata registry for purchases column consolidation.
-- Source: docs/purchases-field-classification.csv (owner-approved 2026-06-26).
-- Rollback: DROP TABLE IF EXISTS purchase_field_registry;

SET @exists := (
  SELECT COUNT(*) FROM information_schema.tables
  WHERE table_schema = DATABASE() AND table_name = 'purchase_field_registry'
);
SET @sql := IF(@exists = 0,
'CREATE TABLE purchase_field_registry (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  column_name VARCHAR(128) NOT NULL,
  kotlin_property VARCHAR(128) NULL,
  json_api_key VARCHAR(255) NULL,
  mysql_type VARCHAR(64) NULL,
  classification VARCHAR(64) NOT NULL,
  target_phase VARCHAR(16) NULL,
  drop_candidate VARCHAR(16) NULL,
  is_indexed VARCHAR(64) NULL,
  query_critical VARCHAR(16) NULL,
  car_brand_mapping_column VARCHAR(128) NULL,
  cost_code_or_json_key VARCHAR(128) NULL,
  notes TEXT NULL,
  review_decision VARCHAR(32) NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_purchase_field_registry_column (column_name),
  KEY idx_pfr_classification (classification),
  KEY idx_pfr_target_phase (target_phase)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

INSERT INTO purchase_field_registry (column_name, kotlin_property, json_api_key, mysql_type, classification, target_phase, drop_candidate, is_indexed, query_critical, car_brand_mapping_column, cost_code_or_json_key, notes, review_decision) VALUES
('id', 'id', 'id', 'BIGINT', 'KEEP', 'N/A', 'NEVER', 'NO', 'NO', NULL, NULL, 'Primary key; never metadata', 'KEEP'),
('date', 'date', 'date', 'VARCHAR(50)', 'KEEP', '0', 'NEVER', 'YES (idx_date)', 'YES', NULL, NULL, 'Rixo buying date; VARCHAR legacy; list/search', 'KEEP'),
('chassis', 'chassis', 'chassis', 'VARCHAR(100)', 'KEEP', 'N/A', 'NEVER', 'YES (idx_chassis)', 'YES', 'chassis', NULL, 'Business key; CSV upsert; not UNIQUE at DB', 'KEEP'),
('car_model_year', 'carModelYear', 'carModelYear', 'VARCHAR(10)', 'VEHICLE_OVERRIDE', '3', 'LATER', 'NO', 'NO', 'car_model_year', 'carModelYear', 'Resolve from map; override if user edits', 'MIGRATE'),
('brand', 'brand', 'brand', 'VARCHAR(100)', 'KEEP', '0', 'NEVER', 'YES (idx_purchases_brand)', 'YES', 'car_brand', NULL, 'Page-search; keep denorm for list performance', 'KEEP'),
('car_name', 'carName', 'carName', 'VARCHAR(100)', 'KEEP', '0', 'LATER', 'YES (idx_car_name)', 'YES', 'car_name', NULL, 'Search + display; may mirror map default', 'KEEP'),
('shipment_size', 'shipmentSize', 'shipmentSize / vehicleType', 'VARCHAR(50)', 'VEHICLE_OVERRIDE', '3', 'LATER', 'NO', 'NO', 'vehicle_type', 'shipmentSize', 'Alias vehicleType in JSON', 'MIGRATE'),
('grade', 'grade', 'grade', 'VARCHAR(100)', 'VEHICLE_OVERRIDE', '3', 'LATER', 'NO', 'NO', 'grade', 'grade', 'Map default + override', 'MIGRATE'),
('rank', 'rank', 'rank', 'VARCHAR(100)', 'VEHICLE_OVERRIDE', '3', 'LATER', 'NO', 'NO', 'rank', 'rank', 'Reserved word column', 'MIGRATE'),
('color', 'color', 'color', 'VARCHAR(100)', 'VEHICLE_OVERRIDE', '3', 'LATER', 'NO', 'NO', 'color', 'color', NULL, 'MIGRATE'),
('fuel', 'fuel', 'fuel', 'VARCHAR(100)', 'VEHICLE_OVERRIDE', '3', 'LATER', 'NO', 'NO', 'fuel', 'fuel', NULL, 'MIGRATE'),
('seat', 'seat', 'seat', 'VARCHAR(100)', 'VEHICLE_OVERRIDE', '3', 'LATER', 'NO', 'NO', 'seat', 'seat', NULL, 'MIGRATE'),
('door', 'door', 'door', 'VARCHAR(100)', 'VEHICLE_OVERRIDE', '3', 'LATER', 'NO', 'NO', 'door', 'door', NULL, 'MIGRATE'),
('distance', 'distance', 'distance', 'VARCHAR(100)', 'VEHICLE_OVERRIDE', '3', 'LATER', 'NO', 'NO', NULL, 'distance', 'Purchase-only; not on chassis map', 'MIGRATE'),
('options', 'options', 'options', 'TEXT', 'EXTENDED_JSON', '4', 'LATER', 'NO', 'NO', NULL, 'options', 'Long text; bundle in extended_attributes', 'MIGRATE'),
('CC', 'cc', 'cc', 'INT', 'VEHICLE_OVERRIDE', '3', 'LATER', 'NO', 'NO', 'cc', 'cc', 'Map stores cc as VARCHAR; purchase as INT', 'MIGRATE'),
('shift', 'shift', 'shift', 'VARCHAR(50)', 'VEHICLE_OVERRIDE', '3', 'LATER', 'NO', 'NO', 'shift', 'shift', NULL, 'MIGRATE'),
('WD', 'wd', 'wd', 'VARCHAR(50)', 'VEHICLE_OVERRIDE', '3', 'LATER', 'NO', 'NO', 'wd', 'wd', NULL, 'MIGRATE'),
('drive_type', 'driveType', 'driveType', 'VARCHAR(50)', 'VEHICLE_OVERRIDE', '3', 'LATER', 'NO', 'NO', 'drive_type', 'driveType', NULL, 'MIGRATE'),
('auction_no', 'auctionNo', 'auctionNo', 'VARCHAR(100)', 'EXTENDED_JSON', '4', 'LATER', 'NO', 'NO', NULL, 'auctionNo', 'Supplier/auction reference', 'MIGRATE'),
('auction_house', 'auctionHouse', 'auctionHouse / auctionName', 'VARCHAR(100)', 'KEEP', '0', 'NEVER', 'YES (idx_purchases_auction_house)', 'YES', NULL, NULL, 'Page-search supplier; links to rixo_prices logically', 'KEEP'),
('stock_location', 'stockLocation', 'stockLocation', 'VARCHAR(100)', 'KEEP', '0', 'LATER', 'NO', 'YES', NULL, NULL, 'Booking filters; distinct dropdowns', 'KEEP'),
('pol', 'pol', 'pol', 'VARCHAR(100)', 'KEEP', '0', 'NEVER', 'NO', 'YES', NULL, NULL, 'Booking + invoice filters', 'KEEP'),
('pod', 'pod', 'pod / destination', 'VARCHAR(255)', 'KEEP', '0', 'LATER', 'NO', 'YES', NULL, NULL, 'JSON alias destination', 'KEEP'),
('rixo_company', 'rixoCompany', 'rixoCompany', 'VARCHAR(100)', 'KEEP', '0', 'LATER', 'NO', 'YES', NULL, NULL, 'Distinct dropdowns; Rixo flow', 'KEEP'),
('client_name', 'clientName', 'clientName', 'VARCHAR(100)', 'KEEP', '0', 'LATER', 'YES (idx_client_name)', 'YES', NULL, NULL, 'Page-search; denorm from clients', 'KEEP'),
('consignee', 'consignee', 'consignee', 'TEXT', 'RESOLVE_CLIENT_MAP', '4', 'LATER', 'NO', 'YES', NULL, NULL, 'Default from client_map; store override only', 'MIGRATE'),
('client_id', 'clientId', 'clientId', 'BIGINT', 'KEEP', 'N/A', 'NEVER', 'YES (idx_purchase_client_id)', 'YES', NULL, NULL, 'FK logical; ledger resolution', 'KEEP'),
('country', 'country', 'country', 'VARCHAR(100)', 'KEEP', '0', 'NEVER', 'NO', 'YES', NULL, NULL, 'Booking country filter', 'KEEP'),
('price', 'price', 'price', 'VARCHAR(50)', 'COST_LINE', '2', 'LATER', 'NO', 'MEDIUM', NULL, 'PRICE', 'Legacy VARCHAR money', 'MIGRATE'),
('auction_fee', 'auctionFee', 'auctionFee', 'VARCHAR(50)', 'COST_LINE', '2', 'LATER', 'NO', 'NO', NULL, 'AUCTION_FEE', NULL, 'MIGRATE'),
('auction_penalty_fee', 'auctionPenaltyFee', 'auctionPenaltyFee', 'VARCHAR(50)', 'COST_LINE', '2', 'LATER', 'NO', 'NO', NULL, 'AUCTION_PENALTY_FEE', NULL, 'MIGRATE'),
('recycle_fee', 'recycleFee', 'recycleFee', 'VARCHAR(50)', 'COST_LINE', '2', 'LATER', 'NO', 'NO', 'recycle_fee', 'RECYCLE_FEE', 'Often from map; still a cost line on purchase', 'MIGRATE'),
('road_tax', 'roadTax', 'roadTax', 'VARCHAR(50)', 'COST_LINE', '2', 'LATER', 'NO', 'NO', NULL, 'ROAD_TAX', NULL, 'MIGRATE'),
('tax_total', 'taxTotal', 'taxTotal', 'VARCHAR(50)', 'COST_LINE', '2', 'LATER', 'NO', 'NO', NULL, 'TAX_TOTAL', NULL, 'MIGRATE'),
('total_price', 'totalPrice', 'totalPrice', 'VARCHAR(50)', 'KEEP', '2', 'NEVER', 'NO', 'YES', NULL, 'TOTAL_PRICE', 'Keep as column for list sort/display; also cost line', 'KEEP'),
('payment_date', 'paymentDate', 'paymentDate', 'VARCHAR(50)', 'EXTENDED_JSON', '4', 'LATER', 'NO', 'NO', NULL, 'paymentDate', NULL, 'MIGRATE'),
('rixo_requested', 'rixoRequested', 'rixoRequested', 'VARCHAR(10)', 'WORKFLOW_CONSOLIDATE', '1', 'YES', 'NO', 'YES', NULL, NULL, 'Legacy VARCHAR; derive from workflow_status', 'MIGRATE'),
('rixo_confirmed', 'rixoConfirmed', 'rixoConfirmed', 'VARCHAR(10)', 'WORKFLOW_CONSOLIDATE', '1', 'YES', 'NO', 'YES', NULL, NULL, 'Booking queries use IN (TRUE,1); migrate before drop', 'MIGRATE'),
('notes', 'notes', 'notes', 'TEXT', 'EXTENDED_JSON', '4', 'LATER', 'NO', 'MEDIUM', NULL, 'notes', NULL, 'MIGRATE'),
('shippment_date', 'shipmentDate', 'shipmentDate / shipmentDate', 'VARCHAR(50)', 'SHIPPING_HISTORY', '4', 'LATER', 'NO', 'YES', NULL, NULL, 'Intentional typo preserved; canonical on shipping_history', 'MIGRATE'),
('B/L_no', 'blNo', 'blNo / B/L_no', 'VARCHAR(100)', 'SHIPPING_HISTORY', '4', 'LATER', 'NO', 'NO', NULL, NULL, 'Reserved word; move to shipping_history', 'MIGRATE'),
('vessel', 'vessel', 'vessel / vesselNo', 'VARCHAR(255)', 'SHIPPING_HISTORY', '4', 'LATER', 'NO', 'YES', NULL, NULL, 'Invoice filter; canonical on shipping_history', 'MIGRATE'),
('booking_requested', 'bookingRequested', 'bookingRequested', 'BOOLEAN/TINYINT', 'WORKFLOW_CONSOLIDATE', '1', 'LATER', 'NO', 'YES', NULL, NULL, 'Dual-write with workflow_status until queries migrated', 'MIGRATE'),
('invoice_confirmed', 'invoiceConfirmed', 'invoiceConfirmed', 'BOOLEAN/TINYINT', 'WORKFLOW_CONSOLIDATE', '1', 'LATER', 'NO', 'YES', NULL, NULL, 'Invoice flow filter', 'MIGRATE'),
('workflow_status', 'workflowStatus', 'workflowStatus', 'VARCHAR(32)/ENUM', 'KEEP', '1', 'NEVER', 'NO', 'YES', NULL, NULL, 'Single workflow source of truth (V29)', 'KEEP'),
('workflow_status_updated_at', 'workflowStatusUpdatedAt', 'workflowStatusUpdatedAt', 'TIMESTAMP', 'KEEP', '1', 'NEVER', 'NO', 'NO', NULL, NULL, 'Audit timestamp for workflow', 'KEEP'),
('shipment_charges', 'shipmentCharges', 'shipmentCharges', 'VARCHAR(50)', 'COST_LINE', '2', 'LATER', 'NO', 'NO', NULL, 'SHIPMENT_CHARGES', 'C&F calculation', 'MIGRATE'),
('freight', 'freight', 'freight', 'VARCHAR(50)', 'COST_LINE', '2', 'LATER', 'NO', 'NO', NULL, 'FREIGHT', NULL, 'MIGRATE'),
('storage_charges', 'storageCharges', 'storageCharges', 'VARCHAR(50)', 'COST_LINE', '2', 'LATER', 'NO', 'NO', NULL, 'STORAGE_CHARGES', NULL, 'MIGRATE'),
('misc_charges', 'miscCharges', 'miscCharges', 'VARCHAR(50)', 'COST_LINE', '2', 'LATER', 'NO', 'NO', NULL, 'MISC_CHARGES', NULL, 'MIGRATE'),
('inspection_fee', 'inspectionFee', 'inspectionFee', 'VARCHAR(50)', 'COST_LINE', '2', 'LATER', 'NO', 'NO', NULL, 'INSPECTION_FEE', NULL, 'MIGRATE'),
('commission', 'commission', 'commission', 'VARCHAR(50)', 'COST_LINE', '2', 'LATER', 'NO', 'NO', NULL, 'COMMISSION', NULL, 'MIGRATE'),
('rixo_price', 'rixoPrice', 'rixoPrice', 'VARCHAR(50)', 'COST_LINE', '2', 'LATER', 'NO', 'NO', NULL, 'RIXO_PRICE', NULL, 'MIGRATE'),
('venue_id', 'venueId', 'venueId', 'VARCHAR(255)', 'EXTENDED_JSON', '4', 'LATER', 'NO', 'MEDIUM', NULL, 'venueId', 'Also on rixo_prices', 'MIGRATE'),
('number_cut', 'numberCut', 'numberCut', 'VARCHAR(255)', 'EXTENDED_JSON', '4', 'LATER', 'NO', 'NO', NULL, 'numberCut', NULL, 'MIGRATE'),
('shaken', 'shaken', 'shaken', 'BOOLEAN/TINYINT', 'EXTENDED_JSON', '4', 'LATER', 'NO', 'NO', NULL, 'shaken', 'Flag', 'MIGRATE'),
('negotiate', 'negotiate', 'negotiate', 'BOOLEAN/TINYINT', 'EXTENDED_JSON', '4', 'LATER', 'NO', 'NO', NULL, 'negotiate', 'V40; flag', 'MIGRATE'),
('repair_company', 'repairCompany', 'repairCompany', 'VARCHAR(100)', 'KEEP', '0', 'LATER', 'NO', 'MEDIUM', NULL, NULL, 'Distinct dropdown query exists', 'KEEP'),
('repair_charges', 'repairCharges', 'repairCharges', 'VARCHAR(50)', 'COST_LINE', '2', 'LATER', 'NO', 'NO', NULL, 'REPAIR_CHARGES', NULL, 'MIGRATE'),
('profit', 'profit', 'profit', 'DECIMAL(15', '2)', 'COST_LINE', '2', 'LATER', 'NO', 'NO', NULL, 'PROFIT', 'APPROVED'),
('is_package_mode', 'isPackageMode', 'isPackageMode', 'BOOLEAN/TINYINT', 'EXTENDED_JSON', '4', 'LATER', 'NO', 'NO', NULL, 'isPackageMode', 'C&F package mode flag', 'MIGRATE'),
('booking_id', 'bookingId', 'bookingId', 'BIGINT', 'KEEP', 'N/A', 'NEVER', 'YES (idx_purchase_booking_id)', 'YES', NULL, NULL, 'Booking group key', 'KEEP'),
('car_pictures', 'carPictures', 'carPictures', 'TEXT', 'EXTENDED_JSON', '4', 'LATER', 'NO', 'NO', NULL, 'carPictures', 'Or separate purchase_media table if blobs grow', 'MIGRATE'),
('created_at', 'createdAt', 'createdAt', 'TIMESTAMP', 'KEEP', 'N/A', 'NEVER', 'NO', 'NO', NULL, NULL, 'Standard audit', 'KEEP'),
('updated_at', 'updatedAt', 'updatedAt', 'TIMESTAMP', 'KEEP', 'N/A', 'NEVER', 'NO', 'NO', NULL, NULL, 'Standard audit', 'KEEP'),
('sold', 'sold', 'sold', 'BOOLEAN', 'DROPPED', 'N/A', 'N/A', 'NO', 'NO', NULL, NULL, 'V33 added V34 dropped; legacy Docker init may still list — do not restore', 'N/A')
ON DUPLICATE KEY UPDATE
  kotlin_property = VALUES(kotlin_property),
  json_api_key = VALUES(json_api_key),
  mysql_type = VALUES(mysql_type),
  classification = VALUES(classification),
  target_phase = VALUES(target_phase),
  drop_candidate = VALUES(drop_candidate),
  is_indexed = VALUES(is_indexed),
  query_critical = VALUES(query_critical),
  car_brand_mapping_column = VALUES(car_brand_mapping_column),
  cost_code_or_json_key = VALUES(cost_code_or_json_key),
  notes = VALUES(notes),
  review_decision = VALUES(review_decision);
