-- Full Number Place list from client sheet (unique Japanese names).
-- Replaces master_menu.number_place so GoDaddy/prod pick up the complete city/ward set on migrate.
-- Format: 日本語 (English). EN spellings aligned to client (e.g. Ichikawa, Ise-Shima, Kitakyushu).
INSERT INTO master_menu (field_name, field_values)
VALUES (
    'number_place',
    '札幌 (Sapporo),函館 (Hakodate),旭川 (Asahikawa),室蘭 (Muroran),苫小牧 (Tomakomai),釧路 (Kushiro),知床 (Shiretoko),帯広 (Obihiro),十勝 (Tokachi),北見 (Kitami),青森 (Aomori),弘前 (Hirosaki),八戸 (Hachinohe),岩手 (Iwate),盛岡 (Morioka),平泉 (Hiraizumi),宮城 (Miyagi),仙台 (Sendai),秋田 (Akita),山形 (Yamagata),庄内 (Shonai),福島 (Fukushima),会津 (Aizu),郡山 (Koriyama),白河 (Shirakawa),いわき (Iwaki),水戸 (Mito),土浦 (Tsuchiura),つくば (Tsukuba),宇都宮 (Utsunomiya),日光 (Nikko),那須 (Nasu),とちぎ (Tochigi),群馬 (Gunma),高崎 (Takasaki),前橋 (Maebashi),千葉 (Chiba),成田 (Narita),野田 (Noda),柏 (Kashiwa),松戸 (Matsudo),習志野 (Narashino),船橋 (Funabashi),市川 (Ichikawa),袖ヶ浦 (Sodegaura),市原 (Ichihara),大宮 (Omiya),川口 (Kawaguchi),熊谷 (Kumagaya),春日部 (Kasukabe),越谷 (Koshigaya),所沢 (Tokorozawa),川越 (Kawagoe),品川 (Shinagawa),世田谷 (Setagaya),足立 (Adachi),江東 (Koto),葛飾 (Katsushika),江戸川 (Edogawa),練馬 (Nerima),杉並 (Suginami),板橋 (Itabashi),多摩 (Tama),八王子 (Hachioji),横浜 (Yokohama),川崎 (Kawasaki),相模 (Sagami),湘南 (Shonan),山梨 (Yamanashi),富士山 (Fujisan),新潟 (Niigata),長岡 (Nagaoka),上越 (Joetsu),長野 (Nagano),松本 (Matsumoto),諏訪 (Suwa),南信州 (Minamishinshu),安曇野 (Azumino),富山 (Toyama),石川 (Ishikawa),金沢 (Kanazawa),名古屋 (Nagoya),三河 (Mikawa),岡崎 (Okazaki),豊田 (Toyota),尾張小牧 (Owari-Komaki),一宮 (Ichinomiya),春日井 (Kasugai),豊橋 (Toyohashi),静岡 (Shizuoka),沼津 (Numazu),伊豆 (Izu),浜松 (Hamamatsu),岐阜 (Gifu),飛騨 (Hida),三重 (Mie),鈴鹿 (Suzuka),四日市 (Yokkaichi),伊勢志摩 (Ise-Shima),福井 (Fukui),大阪 (Osaka),なにわ (Naniwa),和泉 (Izumi),堺 (Sakai),京都 (Kyoto),奈良 (Nara),飛鳥 (Asuka),滋賀 (Shiga),和歌山 (Wakayama),神戸 (Kobe),姫路 (Himeji),広島 (Hiroshima),福山 (Fukuyama),鳥取 (Tottori),島根 (Shimane),出雲 (Izumo),岡山 (Okayama),倉敷 (Kurashiki),山口 (Yamaguchi),下関 (Shimonoseki),徳島 (Tokushima),香川 (Kagawa),高松 (Takamatsu),愛媛 (Ehime),高知 (Kochi),福岡 (Fukuoka),北九州 (Kitakyushu),筑豊 (Chikuho),久留米 (Kurume),佐賀 (Saga),長崎 (Nagasaki),佐世保 (Sasebo),熊本 (Kumamoto),大分 (Oita),宮崎 (Miyazaki),鹿児島 (Kagoshima),奄美 (Amami),沖縄 (Okinawa)'
)
ON DUPLICATE KEY UPDATE field_values = VALUES(field_values);
