-- Rixo price mappings seed (executed inside Docker MySQL container)
USE automan_car_purchase;

CREATE TABLE IF NOT EXISTS rixo_prices (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    auction_name VARCHAR(255) NOT NULL,
    type_of_vehicle VARCHAR(255),
    stock_location VARCHAR(255) NOT NULL,
    rixo_company VARCHAR(255) NOT NULL,
    venue_id VARCHAR(255),
    rixo_price VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DELETE FROM rixo_prices;

INSERT INTO rixo_prices (auction_name, type_of_vehicle, stock_location, rixo_company, venue_id, rixo_price) VALUES
('AUCNETVAA (KISARAZU)', 'CAR, TRUCK', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', '¥8,000'),
('AUCNETVAA (SAKURA)', 'Car', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', '¥8,000'),
('HONDA TOKYO', 'Truck', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', '¥8,000'),
('HONDA KANSAI', 'Car', 'KLC', 'KLC', '', '¥5,500'),
('HONDA NAGOYA', 'Truck', 'GLOBAL NAGOYA', 'STYLISH AUTO', '', '¥5,000'),
('HONDA KYUSHU', 'Car', 'GLOBAL HAKATA', 'Y''S', '', '¥6,820'),
('HONDA SENDAI', 'Truck', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥19,800'),
('HONDA HOKKAIDO', 'Car', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥33,600'),
('JU TOKYO', 'Truck', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', '¥6,000'),
('NOAA', 'Car', 'KLC', 'KLC', '', '¥5,500'),
('CAA TOKYO', 'Car', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', '¥6,000'),
('CAA TOKYO', 'Truck', 'GLOBAL KAWASAKI', 'SHAHBAZ', '', '¥7,000'),
('CAA GIFU', 'Truck', 'GLOBAL NAGOYA', 'STYLISH AUTO', '', '¥7,500'),
('CAA TOHOKU', 'Car', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥28,200'),
('TAA KINKI', 'Truck', 'KLC', 'KLC', '', '¥9,500'),
('TAA KINKI (SHIGA YARD)', 'Car', 'KLC', 'KLC', '', '¥18,000'),
('TAA KYUSHU', 'Truck', 'GLOBAL HAKATA', 'Y''S', '', '¥4,620'),
('TAA MINAMI KYUSHU', 'Car', 'GLOBAL HAKATA', 'Y''S', '', '¥15,400'),
('TAA HIROSHIMA', 'Truck', 'GLOBAL HAKATA', 'Y''S', '', '¥12,000'),
('TAA SHIKOKU', 'Car', 'KLC', 'KLC', '', '¥15,000'),
('TAA SHIKOKU (EHIME)', 'Truck', 'KLC', 'TAA', '', '¥20,000'),
('JU SAITAMA', 'Car', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', '¥7,000'),
('JU SAITAMA', 'Truck', 'GLOBAL KAWASAKI', 'SHAHBAZ', '', '¥7,000'),
('JU SHIZUOKA', 'Car', 'GLOBAL NAGOYA', 'STYLISH AUTO', '', '¥14,000'),
('JU NAGANO', 'Truck', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥26,400'),
('JU MIE', 'Car', 'KLC', 'KLC', '', ''),
('JU YAMAGUCHI', 'Truck', 'GLOBAL HAKATA', 'Y''S', '', ''),
('JU AOMORI', 'Car', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥52,400'),
('JU FUKUI', 'Truck', '-', '-', '', ''),
('NAA FUKUOKA', 'Car', 'GLOBAL HAKATA', 'Y''S', '', '¥3,900'),
('SAA SAPPORO', 'Truck', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥34,600'),
('ORIX KOBE', 'Car', 'KLC', 'KLC', '', '¥5,500'),
('ORIX FUKUOKA', 'Truck', 'GLOBAL HAKATA', 'Y''S', '', '¥3,900'),
('ORIX SENDAI', 'Car', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥19,800'),
('NPS TOKYO', 'Truck', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', '¥7,000'),
('NPS OSAKA', 'Car', 'KLC', 'KLC', '', '¥3,800'),
('NPS SENDAI', 'Truck', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥19,800'),
('NPS FUKUOKA', 'Car', 'GLOBAL HAKATA', 'Y''S', '', ''),
('NPS TOCHIGI', 'Truck', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥13,200'),
('NPS TOMAKOMAI', 'Car', 'GLOBAL KAWASAKI', 'LOGICO', '', ''),
('LUM NAGOYA', 'Truck', 'GLOBAL NAGOYA', 'LOGICO', '', '¥6,000'),
('LUM FUKUOKA', 'Car', 'GLOBAL HAKATA', 'LOGICO', '', '¥6,200'),
('USS YOKOHAMA', 'Car', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', '¥4,000'),
('USS YOKOHAMA', 'Truck', 'GLOBAL KAWASAKI', 'SHAHBAZ', '', '¥3,500'),
('USS YOKOHAMA', 'TRUCKS BUS', '', '', '', '¥8,000'),
('USS R-NAGOYA', 'Car', 'GLOBAL NAGOYA', 'STYLISH AUTO', '', '¥5,000'),
('CAA CHUBU', 'Truck', 'GLOBAL NAGOYA', 'STYLISH AUTO', '', '¥6,000'),
('BAYAUC', 'Car', 'KLC', 'KLC', '', '¥5,000'),
('IAA OSAKA', 'Truck', 'KLC', 'KLC', '', '¥3,800'),
('LAA SHIKOKU', 'Car', 'KLC', 'KLC', '', '¥15,000'),
('HERO', 'Truck', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', '¥10,000'),
('KCAA MINAMI KYUSHU', 'Car', 'GLOBAL HAKATA', 'Y''S', '', '¥14,300'),
('KCAA KYOTO', 'Truck', 'KLC', 'KLC', '', '¥9,500'),
('ISUZU TOKYO', 'Car', 'GLOBAL KAWASAKI', '-', '', ''),
('MIRIVE SAITAMA', 'Truck', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥10,800'),
('JU IBARAKI', 'Car', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥14,400'),
('JU ISHIKAWA', 'Truck', 'GLOBAL NAGOYA', 'LOGICO', '', '¥16,600'),
('JU KUMAMOTO', 'Car', 'GLOBAL HAKATA', 'Y''S', '', '¥12,100'),
('JU OITA', 'Truck', 'GLOBAL HAKATA', 'Y''S', '', ''),
('JU NAGASAKI', 'Car', 'GLOBAL HAKATA', 'Y''S', '', ''),
('ORIX ATSUGI', 'Truck', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥8,900'),
('ORIX ATSUGI (OYAMA)', 'Car', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥13,200'),
('LUM TOKYO', 'Truck', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥9,600'),
('LUM TOKYO (SENDAI)', 'Car', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥19,800'),
('USS SAPPORO', 'Car', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥34,600'),
('USS TOHOKU', 'Truck', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥19,400'),
('USS NIIGATA', 'Car', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥22,200'),
('USS KOBE', 'Truck', 'KLC', 'KLC', '', '¥5,500'),
('USS FUKUOKA', 'Car', 'GLOBAL HAKATA', 'Y''S', '', '¥4,620'),
('JAA', 'Car', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', '¥6,000'),
('JAA', 'Truck', 'GLOBAL KAWASAKI', 'SHAHBAZ', '', '¥6,000'),
('TAA CHUBU', 'Car', 'GLOBAL NAGOYA', 'STYLISH AUTO', '', '¥5,000'),
('TAA CHUBU (SHIZUOKA)', 'Truck', 'GLOBAL NAGOYA', 'STYLISH AUTO', '', '¥13,000'),
('TAA CHUBU (HOKURIKU)', 'Car', 'GLOBAL NAGOYA', 'STYLISH AUTO', '', '¥18,000'),
('TAA CHUBU (HOKURIKU)', 'Truck', 'GLOBAL NAGOYA', 'LOGICO', '', '¥16,600'),
('TAA KANTO', 'Truck', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', '¥6,000'),
('TAA KANTO', 'CAR', 'GLOBAL KAWASAKI', 'SHAHBAZ', '', '¥6,000'),
('TAA KANTO', 'BIG CAR/TRUCK', 'GLOBAL KAWASAKI', 'SHAHBAZ', '', '¥8,000'),
('TAA KANTO (KITA KANTO)', 'Car', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥12,000'),
('TAA KANTO (SAITAMA)', 'Truck', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', '¥7,000'),
('TAA KANTO (SAITAMA)', 'Car', 'GLOBAL KAWASAKI', 'SHAHBAZ', '', '¥8,000'),
('TAA KANTO (TAMA)', 'Truck', 'GLOBAL KAWASAKI', 'TAA', '', '¥12,000'),
('TAA TOHOKU', 'Car', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥18,000'),
('TAA TOHOKU (MIYAGI)', 'Truck', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥19,800'),
('TAA HOKKAIDO', 'Car', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥34,600'),
('KCAA FUKUOKA', 'Truck', 'GLOBAL HAKATA', 'Y''S', '', '¥3,900'),
('MIRIVE OSAKA', 'Car', 'KLC', 'KLC', '', '¥6,000'),
('ARAI OYAMA', 'Truck', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', '¥10,000'),
('ARAI OYAMA', 'CAR', 'GLOBAL KAWASAKI', 'SHAHBAZ', '', '¥10,000'),
('ARAI OYAMA', 'HIACE', 'GLOBAL KAWASAKI', 'SHAHBAZ', '', '¥12,000'),
('ARAI OYAMA', 'TRUCKS', 'GLOBAL KAWASAKI', 'SHAHBAZ', '', '¥18,000'),
('NAA NAGOYA', 'Car', 'GLOBAL NAGOYA', 'STYLISH AUTO', '', '¥7,000'),
('NAA NAGOYA (HOKURIKU)', 'Truck', 'GLOBAL NAGOYA', 'STYLISH AUTO', '', '¥28,000'),
('NAA NAGOYA (HOKURIKU)', 'Car', 'GLOBAL NAGOYA', 'HIDA', '', '¥15,000'),
('NAA OSAKA', 'Truck', 'KLC', 'KLC', '', '¥5,500'),
('JU AICHI', 'Car', 'GLOBAL NAGOYA', 'STYLISH AUTO', '', '¥4,000'),
('JU HIROSHIMA', 'Truck', 'GLOBAL HAKATA', 'Y''S', '', '¥14,300'),
('JU FUKUSHIMA', 'Car', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥18,000'),
('JU GUNMA', 'Truck', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥12,000'),
('JU KANAGAWA', 'Car', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥12,000'),
('JU KANAGAWA', 'Truck', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', ''),
('JU KANAGAWA', 'Car', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥12,000'),
('JU TOYAMA', 'Truck', 'GLOBAL NAGOYA', 'STYLISH AUTO', '', ''),
('JU TOYAMA', 'Car', 'GLOBAL NAGOYA', 'LOGICO', '', '¥18,100'),
('JU MIYAZAKI', 'Truck', 'GLOBAL HAKATA', 'Y''S', '', ''),
('ZIP OSAKA', 'Car', 'KLC', 'KLC', '', '¥5,500'),
('SAA HAMAMATSU', 'Truck', 'GLOBAL NAGOYA', 'STYLISH AUTO', '', '¥10,000'),
('ISUZU KYUSHU', 'Car', 'GLOBAL HAKATA', 'Y''S', '', '¥4400 | ¥7700'),
('LUM HOKKAIDO', 'Truck', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥33,600'),
('LUM KOBE', 'Car', 'KLC', 'LOGICO', '', '¥6,500'),
('LUM KOBE (HIROSHIMA)', 'Truck', 'GLOBAL HAKATA', 'LOGICO', '', '¥30,600'),
('ZERO SHONAN', 'Car', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥8,900'),
('ZERO OSAKA', 'Truck', 'KLC', 'KLC', '', ''),
('USS TOKYO', 'CAR', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', '¥7,000'),
('USS TOKYO', 'CAR', 'GLOBAL KAWASAKI', 'SHAHBAZ', '', '¥7,000'),
('USS TOKYO', 'G CLASS/ LAND CRUISER/', 'GLOBAL KAWASAKI', 'SHAHBAZ', '', '¥10,000'),
('USS TOKYO', 'TRUCKS', 'GLOBAL KAWASAKI', 'SHAHBAZ', '', '¥15,000'),
('JU FUKUOKA', 'Car', 'GLOBAL HAKATA', 'Y''S', '', '¥3,900'),
('JU MIYAGI', 'Truck', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥19,400'),
('JU CHIBA', 'Car', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', '¥8,000'),
('JU CHIBA', 'Truck', 'GLOBAL KAWASAKI', 'SHAHBAZ', '', '¥7,000'),
('JU NIIGATA', 'Car', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥22,200'),
('JU TOCHIGI', 'Truck', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥13,200'),
('JU OKINAWA', 'Car', '-', '-', '', ''),
('JU HOKKAIDO', 'Truck', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥34,600'),
('JU SHIMANE', 'Car', '-', '-', '', ''),
('ARAI BAYSIDE', 'Car', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', '¥3,000'),
('ARAI BAYSIDE', 'Truck', 'GLOBAL KAWASAKI', 'SHAHBAZ', '', '¥3,000'),
('ARAI BAYSIDE (DAI 2 YARD)', 'Car', 'GLOBAL KAWASAKI', 'SHAHBAZ', '', '¥3,500'),
('ARAI SENDAI', 'Truck', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥19,800'),
('LAA OKAYAMA', 'Car', 'KLC', 'KLC', '', '¥10,800'),
('NAA TOKYO', 'CAR', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', '¥4,000'),
('NAA TOKYO', 'CAR', 'GLOBAL KAWASAKI', 'SHAHBAZ', '', '¥3,500'),
('KCAA YAMAGUCHI', 'Truck', 'GLOBAL HAKATA', 'Y''S', '', '¥10,200'),
('ISUZU KOBE', 'Car', 'KLC', 'KLC', '', '¥14,000'),
('ISUZU KOBE (SAKURAI YARD)', 'Truck', 'KLC', 'KLC', '', '¥28,000'),
('MIRIVE AICHI', 'Car', 'GLOBAL NAGOYA', 'STYLISH AUTO', '', '¥6,000'),
('ZERO HOKKAIDO', 'Truck', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥33,600'),
('ZERO SENDAI', 'Car', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥19,800'),
('ZERO CHIBA', 'Truck', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', '¥7,000'),
('ZERO HAKATA', 'Car', 'GLOBAL HAKATA', 'Y''S', '', '¥7,200'),
('USS SAITAMA', 'Truck', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', '¥8,000'),
('USS NAGOYA', 'Car', 'GLOBAL NAGOYA', 'STYLISH AUTO', '', '¥5,000'),
('USS OSAKA', 'Truck', 'KLC', 'KLC', '', '¥5,500'),
('JU GIFU', 'Car', 'GLOBAL NAGOYA', 'STYLISH AUTO', '', '¥7,500'),
('JU NARA', 'Truck', 'KLC', 'KLC', '', '¥9,500'),
('JU YAMAGATA', 'Car', 'GLOBAL KAWASAKI', 'LOGICO', '', ''),
('JU YAMANASHI', 'Truck', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥21,600'),
('TAA YOKOHAMA', 'Car', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', '¥9,000'),
('TAA YOKOHAMA', 'Truck', 'GLOBAL KAWASAKI', 'SHAHBAZ', '', '¥3,500'),
('TAA YOKOHAMA (ATSUGI)', 'Car', 'GLOBAL KAWASAKI', 'TAA', '', '¥9,900'),
('TAA HYOGO', 'Truck', 'KLC', 'KLC', '', '¥5,500'),
('ZIP TOKYO', 'Car', 'GLOBAL KAWASAKI', 'YAMAZAKI', '', '¥8,000'),
('ZIP TOKYO', 'Truck', 'GLOBAL KAWASAKI', 'SHAHBAZ', '', '¥6,000'),
('USS GUNMA', 'Car', 'GLOBAL KAWASAKI', 'LOGICO', '', '¥13,200'),
('USS HOKURIKU', 'Truck', 'GLOBAL NAGOYA', 'LOGICO', '', '¥19,800'),
('USS HOKURIKU', 'Car', 'GLOBAL NAGOYA', 'STYLISH AUTO', '', '¥18,000'),
('USS SHIZUOKA', 'Truck', 'GLOBAL NAGOYA', 'STYLISH AUTO', '', '¥13,000'),
('USS OKAYAMA', 'Car', 'KLC', 'KLC', '', '¥10,800'),
('USS KYUSHU', 'Truck', 'GLOBAL HAKATA', 'Y''S', '', '¥4,620'),
('HAA KOBE', 'Car', 'KLC', 'KLC', '', '¥5,500'),
('HAA KOBE', 'Truck', 'ECL KOBE', 'KLC', '', '¥4,500');

