package com.automan.purchase

data class Purchase(
    val id: Long? = null,
    val date: String? = null,
    val chassis: String,
    val carModelYear: String? = null,
    val brand: String? = null,
    val carName: String? = null,
    val grade: String? = null,
    val rank: String? = null,
    val color: String? = null,
    val displacement: String? = null,
    val fuel: String? = null,
    val seat: String? = null,
    val door: String? = null,
    val distance: String? = null,
    val options: String? = null,
    val auctionNo: String? = null,
    val auctionHouse: String? = null,
    val stockLocation: String? = null,
    val rixoCompany: String? = null,
    val clientName: String? = null,
    val country: String? = null,
    val price: String? = null,
    val auctionFee: String? = null,
    val recycleFee: String? = null,
    val roadTax: String? = null,
    val taxTotal: String? = null,
    val totalPrice: String? = null,
    val paymentDate: String? = null,
    val rixoRequested: String? = null,
    val rixoConfirmed: String? = null,
    val notes: String? = null,
    val shipmentDate: String? = null,
    val blNo: String? = null,
    val vesselNo: String? = null,
    val destination: String? = null,
    val shipmentCharges: String? = null,
    val freight: String? = null,
    val storageCharges: String? = null,
    val miscCharges: String? = null,
    val inspectionFee: String? = null,
    val commission: String? = null,
    val rixoPrice: String? = null,
    val repairCompany: String? = null,
    val repairCharges: String? = null
)
