#!/usr/bin/env python3
"""
Regenerate MySQL seed SQL for `rixo_mapping` from the price sheet CSV.

Source: RIXO PRICE SHEET.csv (project root)
Columns: RIXO COMPANY, AUCTION Name, STOCK LOCATION, Supported Vehicle Type, RATE

Usage:
  python3 scripts/regenerate_rixo_mapping_sql.py
  python3 scripts/regenerate_rixo_mapping_sql.py --csv "RIXO PRICE SHEET.csv"
  python3 scripts/regenerate_rixo_mapping_sql.py --write-flyway

Outputs:
  - database/rixo_mapping_from_price_sheet.sql  (DELETE + INSERT only; run after `auction_name` exists)
  - With --write-flyway: also overwrites
    backend/src/main/resources/db/migration/V2__rixo_mapping_auction_name.sql
    (ALTER + DELETE + INSERT). Only use if Flyway V2 has not been applied yet, or create a new
    V3 migration instead of editing V2 on deployed databases (checksum mismatch).

Also updates database/01-init-multiplatform.sql: replaces the rixo_mapping INSERT block when --patch-init is passed.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path


def project_root() -> Path:
    return Path(__file__).resolve().parent.parent


def sql_string(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "''") + "'"


def parse_rows(csv_path: Path) -> list[tuple[str, str | None, str, str | None, str | None]]:
    rows: list[tuple[str, str | None, str, str | None, str | None]] = []
    with csv_path.open(newline="", encoding="utf-8-sig") as f:
        reader = csv.reader(f)
        header = next(reader, None)
        if not header:
            raise SystemExit("CSV is empty")
        for row in reader:
            while len(row) < 5:
                row.append("")
            company = row[0].strip()
            auction = row[1].strip()
            stock = row[2].strip()
            vtype = row[3].strip()
            rate = row[4].strip()
            if not company and not auction and not stock:
                continue
            if not company or not stock:
                print(f"skip row (missing company or stock): {row!r}", file=sys.stderr)
                continue
            rows.append(
                (
                    company,
                    auction if auction else None,
                    stock,
                    vtype if vtype else None,
                    rate if rate else None,
                )
            )
    return rows


def build_delete_insert(rows: list[tuple[str, str | None, str, str | None, str | None]]) -> str:
    lines = [
        "-- Generated by scripts/regenerate_rixo_mapping_sql.py — do not edit by hand.",
        f"-- Rows: {len(rows)}",
        "",
        "DELETE FROM rixo_mapping;",
        "",
        "INSERT INTO rixo_mapping (rixo_company, auction_name, stock_location, supported_vehicle_type, rixo_price) VALUES",
    ]
    value_lines = []
    for company, auction, stock, vtype, rate in rows:
        parts = [
            sql_string(company),
            sql_string(auction) if auction is not None else "NULL",
            sql_string(stock),
            sql_string(vtype) if vtype is not None else "NULL",
            sql_string(rate) if rate is not None else "NULL",
        ]
        value_lines.append("(" + ", ".join(parts) + ")")
    lines.append(",\n".join(value_lines) + ";")
    lines.append("")
    return "\n".join(lines)


def build_flyway_v2(body_delete_insert: str, row_count: int) -> str:
    """Prepend Flyway header + ALTER; keep full DELETE + INSERT from build_delete_insert."""
    b = body_delete_insert.strip()
    lines = b.split("\n")
    i = 0
    while i < len(lines) and lines[i].startswith("--"):
        i += 1
    while i < len(lines) and lines[i].strip() == "":
        i += 1
    core = "\n".join(lines[i:])
    return f"""-- Adds auction house name from RIXO PRICE SHEET.csv and replaces all rixo_mapping rows ({row_count}).
-- Regenerated by scripts/regenerate_rixo_mapping_sql.py

ALTER TABLE rixo_mapping ADD COLUMN auction_name VARCHAR(255) NULL AFTER rixo_company;

{core}
"""


def patch_01_init(init_path: Path, body_delete_insert: str) -> None:
    text = init_path.read_text(encoding="utf-8")
    # Remove our generator comments from body — use INSERT through final `);`
    m = re.search(
        r"-- RIXO PRICE SHEET\.csv[^\n]*\nINSERT INTO rixo_mapping \(rixo_company, auction_name, stock_location, supported_vehicle_type, rixo_price\) VALUES\n[\s\S]*?\);",
        text,
    )
    if not m:
        raise SystemExit(
            f"Could not find rixo_mapping INSERT block in {init_path}. Patch 01-init manually."
        )
    new_block = "-- RIXO PRICE SHEET.csv (includes auction_name)\n" + body_delete_insert.split(
        "DELETE FROM rixo_mapping;\n\n", 1
    )[-1].strip()
    text = text[: m.start()] + new_block + text[m.end() :]
    init_path.write_text(text, encoding="utf-8")
    print(f"Wrote patch: {init_path}")


def main() -> None:
    ap = argparse.ArgumentParser(description="Regenerate rixo_mapping SQL from RIXO PRICE SHEET.csv")
    ap.add_argument(
        "--csv",
        type=Path,
        default=None,
        help="Path to CSV (default: <repo>/RIXO PRICE SHEET.csv)",
    )
    ap.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output SQL path (default: database/rixo_mapping_from_price_sheet.sql)",
    )
    ap.add_argument(
        "--write-flyway",
        action="store_true",
        help="Also write backend/.../V2__rixo_mapping_auction_name.sql (ALTER+DELETE+INSERT)",
    )
    ap.add_argument(
        "--patch-init",
        action="store_true",
        help="Also replace rixo_mapping INSERT block in database/01-init-multiplatform.sql",
    )
    args = ap.parse_args()
    root = project_root()
    csv_path = args.csv or (root / "RIXO PRICE SHEET.csv")
    if not csv_path.is_file():
        raise SystemExit(f"CSV not found: {csv_path}")

    rows = parse_rows(csv_path)
    body = build_delete_insert(rows)
    out = args.out or (root / "database" / "rixo_mapping_from_price_sheet.sql")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(body, encoding="utf-8")
    print(f"Wrote {out} ({len(rows)} rows)")

    if args.write_flyway:
        v2_path = root / "backend" / "src" / "main" / "resources" / "db" / "migration" / "V2__rixo_mapping_auction_name.sql"
        v2_path.write_text(build_flyway_v2(body, len(rows)), encoding="utf-8")
        print(f"Wrote {v2_path}")

    if args.patch_init:
        patch_01_init(root / "database" / "01-init-multiplatform.sql", body)


if __name__ == "__main__":
    main()
